version: '3.1'

services:

  mongodbi:
    image: mongo
    restart: always
    hostname: mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin